### ISSUE TITLE
npm dependency issue (missing 'node-xmpp-client' and 'q')

### ISSUE THREAD

**Issue by KraigM** [swissmanu/harmonyhubjs-client#16]
When I install version 1.1.7, it only installs:
```
harmonyhubjs-client@1.1.7 node_modules/harmonyhubjs-client
├── node-xmpp-core@4.2.0 (ltx@2.2.0)
└── node-xmpp-stanza@1.1.0 (ltx@2.2.0)
```
which then blows up because it is missing the other dependencies
```
====================
ERROR LOADING PLUGIN homebridge-harmonyhub:
Error: Cannot find module 'node-xmpp-client'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kraigm/git/HomeAutomation/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/login/hub.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
====================
```

I think it may have to do with shrinkwrap but I have never used that so Im not even sure how it works.  All I know is the two dependencies that resolved were the only ones specified in the shrinkwrap

**Comment by swissmanu** [comment]
Did you a "clean install" or just an update?
Further is this issue really related to `q`? I see the dependency clearly declared in the `package.json` and your stacktraces do not mention anything about it :)

There are currently some dependency problems regarding `node-xmpp-*` and `ltx` I'm trying to solve currently.
I want the xmpp modules to use a customized version of `ltx` which is not that easy is I wanted to be :-/

**Comment by swissmanu** [comment]
Okay... As far as I can verify, version `1.1.8` should fix the mess with `node-xmpp-*` and `ltx`.

Please make sure you are using the latest version of `npm` (`npm install npm -g`) and try to install the newest version `1.1.8` of `harmonyhubjs-client` (release notes here: https://github.com/swissmanu/harmonyhubjs-client/releases/tag/v1.1.8)

**Comment by KraigM** [comment]
I worked around it by re-shrinkwrapping it but its gross (https://github.com/KraigM/homebridge-harmonyhub/blob/master/npm-shrinkwrap.json).  I will try this without my shrinkwrap when I get a chance. Thanks!

And thanks for the awesome modules.  They made my life so much easier when integrating harmony hub with Siri (https://github.com/KraigM/homebridge-harmonyhub)  has had a lot of happy users including me :smile:

**Comment by swissmanu** [comment]
thank you for your kind words @KraigM! really appreciate :)
awesome what you built with your homebridge plugin btw. have to give it a testdrive once.
