### ISSUE TITLE
Error installing 1.1.8

### ISSUE THREAD

**Issue by Rollonat** [swissmanu/harmonyhubjs-client#21]
Hi,
how can the version 1.1.8 be installed ? here is my log:
root@raspberrypi:/usr/src/homebridge# npm install -g https://github.com/swissmanu/harmonyhubjs-client/archive/v1.1.8.tar.gz
npm ERR! Linux 4.1.6-v7+
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "https://github.com/swissmanu/harmonyhubjs-client/archive/v1.1.8.tar.gz"
npm ERR! node v0.12.6
npm ERR! npm  v3.6.0

npm ERR! No version provided
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/homebridge/npm-debug.log

**Comment by swissmanu** [comment]
are you simply using `npm install -g harmonyhubjs-client` or are you trying to install directly via the git repository?

**Comment by swissmanu** [comment]
closed by inactivity.
