### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by maddox** [swissmanu/harmonyhubjs-client#22]
I get timeouts all the time when requesting the list activities with the client. These aren't caught in any ways and makes the client crash immediately.

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ETIMEDOUT
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:550:26)
```

Hopefully there can be some graceful handling of these inside the client itself.

**Comment by swissmanu** [comment]
is this related to #8? maybe you can have a look at https://github.com/swissmanu/orchestra-jsapi which has already a keep-alive workaround implemented.

otherwise i would really welcome a mechanism for handling these timeouts.
