### ISSUE TITLE
Stopping activities broken

### ISSUE THREAD

**Issue by brian-gates** [swissmanu/harmonyhubjs-client#25]
Hi there,

First, awesome lib.  Great work.

However, using your examples turns devices on, but does not turn them back off.  Perhaps there was a shift in the API?

Any help would be appreciated :)

**Comment by swissmanu** [comment]
hi brian

what does `getActivities()` return? is there an activity with the id `-1`?
if so, API is most probably the same as before.

thx for confirmation,
manu

**Comment by brian-gates** [comment]
There is an item with -1.  Its label is 'PowerOff'.

startActivity -1 does turn _everything_ off.  

Is it possible to turn off a single device by id?

**Comment by brian-gates** [comment]
`client.isOff().then(log)` seems to always output `true` regardless of device state.  I think that's why your demo script doesn't toggle as it should.

Activities have a property `controlGroup` which hint at useful functionalities like `Volume`, `Channel`, `DisplayMode`.  Are these somehow accessible?

**Comment by swissmanu** [comment]
* `isOff` and `turnOff` is meant to turn off the complete system, not specific devices.
* if you are interested in interacting with your devices explicitly, have a look into the source code of https://github.com/swissmanu/orchestra-jsapi. that library tries to abstract this kind of interaction further away.

**Comment by brian-gates** [comment]
Thanks for the information.  

I still think there's a bug though: `isOff` doesn't return false after turning a device on.

I'll take a look at `orchestra-jsapi`.  I'm guessing [executeAction](https://github.com/swissmanu/orchestra-jsapi/blob/master/index.js#L89) is what I'm looking for?

**Comment by brian-gates** [comment]
Main goal is to turn off a single device (by id or name).  Not sure if `executeAction` will accomplish this, or how. 

Any help is appreciated!

**Comment by bradwbradw** [comment]
@brian-gates  i know it's been 3 years, but i'm having the exact same problem.  Were you able to figure out how to end an activity?
