### ISSUE TITLE
Question: How to handle connection losses?

### ISSUE THREAD

**Issue by netactivenl** [swissmanu/harmonyhubjs-client#30]
Hi,

Unfortunately I'm totally unfamiliar with the XMPP protocol and the internals of the harmonyhubjs-client. Does the harmonyhubjs-client expose connection state or connection state events somehow? 

I'm using the client in an application that keeps an open connection to the hub. If for some reason the connection gets lost (or the connection state would change), it would be great if an event was emitted. That way my application can handle lost connections, by for instance trying to reconnect to the hub.

Hopefully someone can help me out.

Best regards,
Raymond

**Comment by swissmanu** [comment]
hi raymond

the underlying XMPP client emits an `offline` event once the connection disappears. though `harmonyhubjs-client` it does no effort on maintaining a permanent connection.

make sure you have a look at `orchestra-jsapi`. it encapsulates both `harmonyhubjs-client` and `harmonyhubjs-discover` and implements a simple connection management so the actual consumer does not have to worry about closed connections.

if you are interested in particular how the management is solved, have a look at https://github.com/swissmanu/orchestra-jsapi/blob/master/index.js#L41

**Comment by hufftheweevil** [comment]
I've found a very simple fix to this issue. Please see PR #42
