### ISSUE TITLE
Events for Activity Changes?

### ISSUE THREAD

**Issue by docbobo** [swissmanu/harmonyhubjs-client#35]
Is there any way to get notifications of changes to the currently running activity?

**Comment by swissmanu** [comment]
you can use the hubs `stateDigest` stanza to detect such things:
https://github.com/swissmanu/harmonyhubjs-client/blob/develop/docs/protocol/stateDigest.md

see [orchestra-jsapi](https://github.com/swissmanu/orchestra-jsapi/blob/master/index.js#L47) for an example.
