### ISSUE TITLE
NPM Install results in ENOENT with Dependencies LTX

### ISSUE THREAD

**Issue by jlong23** [swissmanu/harmonyhubjs-client#38]
https://github.com/swissmanu/harmonyhubjs-client/blob/f6e165eb5b560ea53dd40230bfb6284627a51b69/package.json#L30

npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! not a package /tmp/npm-17423-xgU6Dk0q/github.com/swissmanu/ltx.git
info trying registry request attempt 1 at 06:32:31
http GET https://registry.npmjs.org/ms
http 304 https://registry.npmjs.org/ms
npm ERR! Error: ENOENT, open '/tmp/npm-17423-xgU6Dk0q/github.com/swissmanu/ltx.git-unpack/package.json'

I think it may be malformed.

**Comment by swissmanu** [comment]
is this still a problem?
