### ISSUE TITLE
Can't connect to hub

### ISSUE THREAD

**Issue by github22222** [swissmanu/harmonyhubjs-client#41]
This used to work but now it does not. This is the error output:

Connecting to hub at 192.168.1.***
errorhub { Error: connect ETIMEDOUT 192.168.1.***:5222
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.***',
  port: 5222 }

**Comment by swissmanu** [comment]
check your network connection and/or try to rediscover you hub useing `harmonyhubjs-discover`.

**Comment by github22222** [comment]
Thanks for the comment but it does not help me except to be sure that it is of course a problem with my setup not your project. I had been using your project and the other code for a number of years along with Alexa. Logitech has started supporting skills with Alexa so I have gotten away from doing my own as a hobby. The hub works fine and I had always used the local ip given in the DHCP Client Table without issue. Why it does not work now is beyond me. I am by far no expert on networks.

**Comment by swissmanu** [comment]
there was no new release recently. i only can assume that something in your set up changed, either network or software wise 😔
maybe you can try investigate based on your nodejs version or something. otherwise there is really nothing i can do for you based on the stacktrace you provided.

**Comment by github22222** [comment]
It works now after allowing public in addition to private communication through the firewall for node.js: Server-side JavaScript. I thought of it after my ftp server stopped responding and I had to allow it access. Thanks again for the feedback.
