### ISSUE TITLE
Fertig mit Fehler: reading io-package.json Error: ENOENT: no such file or directory, open 'null/io-package.json'

### ISSUE THREAD

**Issue by Master6726** [swissmanu/harmonyhubjs-client#45]
Erhalte beim Installieren über ioBroker folgende Fehlermeldung, ich muss dazu sagen das die app bis vor 14 Tagen gelaufen ist dann bin ich auf Debian 9.5 Umgezogen, danach liefe die App nicht mehr, Deinstalliert und nun lässt sie sich nicht mehr Installieren seihe Fehlermeldung:

``$ ./iobroker add harmony  --host ioBroker
NPM version: 4.6.1
npm install iobroker.harmony --production --save --prefix "/opt/iobroker" (System call)
npm WARN addRemoteGit
 Error: not found: gitnpm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git+https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser resetting remote /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/swissmanu/ltx.git /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/swissmanu/ltx.git /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefined

npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! code
 ENOGITnpm 
ERR! not found: gitnpm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-18T18_42_08_194Z-debug.log

host.ioBroker create instance harmony
ERROR: host.ioBroker error: reading io-package.json Error: ENOENT: no such file or directory, open 'null/io-package.json'
ERROR: process exited with code 20

**Comment by swissmanu** [comment]
hi. for issues regarding iobroker, please consider an issue in the regarding repository. thanks.
