### ISSUE TITLE
listen for activities

### ISSUE THREAD

**Issue by Pmant** [swissmanu/harmonyhubjs-client#6]
Is it possible to listen for activity changes and do something when an activity starts / ends? I know I just could repeatedly check the current activity but maybe there is a better way.

**Comment by swissmanu** [comment]
the hub publishes state digest messages as soon as an activity is started, in progress or stopped. `harmonyhubjs` has already a mechanism to listen for these digest messages (see [harmonyclient.js#L55](https://github.com/swissmanu/harmonyhubjs-client/blob/master/lib/harmonyclient.js#L55)).
you can register to `harmonyhubjs`' `stateDigest` event with:

```javascript
client.on('stateDigest', function(digest) { /* ... */ });
```

please refer to the protocol documents for further information about the state digest message: [State Digest](https://github.com/swissmanu/harmonyhubjs-client/blob/master/docs/protocol/stateDigest.md).

if you're interested into a higher abstraction of `harmonhubjs-client`/`harmonyhubjs-discover`, have a look at [orchestra-jsapi](https://github.com/swissmanu/orchestra-jsapi). it encapsulates both libraries and uses the event subscription mechanism above in the exact same way. (see [index.js#L40](https://github.com/swissmanu/orchestra-jsapi/blob/master/index.js#L40))

**Comment by Pmant** [comment]
Thank you, this helped me a lot!
With the code below I'm able to log activity starts/ends, but after about 60 seconds the script exits, the client seems to time out.
```javascript
var harmony = require('harmonyhubjs-client');

harmony('192.168.0.58').then(function(harmonyClient) {
    console.log('hub client started');
    harmonyClient.on('stateDigest', function(digest) {
        console.log('stateDigest: ' + JSON.stringify(digest));
    });
}).catch(function(e){
    console.log('error');
});
```

**Comment by Pmant** [comment]
harmonyClient._xmppClient.connection.reconnect = true;
this helps but still disconnects every minute as I can see with
```javascript
harmonyClient._xmppClient.connection.socket.on('close', function(e) {
    console.log('socket closed');
});
```
I also tried 
```
harmonyClient._xmppClient.connection.socket.setTimeout(0);
harmonyClient._xmppClient.connection.socket.setKeepAlive(true,10000);
```

**Comment by swissmanu** [comment]
I came across the same problem when implementing `orchestra` once.
Though, I was not able to find the actual cause of it. I worked around by implementing a reconnect mechanism on myself (see https://github.com/swissmanu/orchestra-jsapi/blob/master/index.js#L34)

Don't know if this disconnect happens upon Logitechs intention :-/

**Comment by Pmant** [comment]
I was able to prevent the disconnect by periodically sending a command to the server:
```javascript
! function keepAlive(){
    harmonyClient.request('getCurrentActivity').timeout(5000).then(function(response) {
        setTimeout(keepAlive, 10000);
    }).catch(function(e){
        adapter.log.warn('keep alive cannot get current Activity: ' + e);
    });
}();
```
